### ISSUE TITLE
3. why is the gc copying all the pages in the block each time and not only some of them ? the GARBAGE_COLLECTION method is writing the "write amplification" stats to the socket but for some reason it's always 9. i already removed the += but i need to understand why the copy_page_nb is 9 (is this a bug?)

### ISSUE THREAD

**Issue by davidsaOpenu** [davidsaOpenu/simulator#9]

**Comment by eyalfishel** [comment]
I started debugging it, and copy_page_nb is 2 or 3, which according to the code is not a bug.
In what revision did this happen?

**Comment by ialexyi** [comment]
It isn't a bug.
The flash device can't rewrite a single page, because erase operation required.
The minimal erase operation can erase block not a page.
In this case block is 10 pages.
After erase the block, the data of 9 page must be written back.
This is a reason of 9 over writes for each written new page.

**Comment by davidsaOpenu** [comment]
Great. Thanks, guys!

**Comment by davidsaOpenu** [comment]
So  that means we have a dumb CG algorithm :-(
